import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fuutura Pakistan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} bg-[#0B0B0D] ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <div className="w-full bg-black">
          <img className="mx-auto" src="/footer.png" alt="" />
        </div>
      </body>
    </html>
  );
}